# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1123, 865)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.central_widget.sizePolicy().hasHeightForWidth())
        self.central_widget.setSizePolicy(sizePolicy)
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setSpacing(6)
        self.main_layout.setObjectName("main_layout")
        self.control_layout = QtWidgets.QGridLayout()
        self.control_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.control_layout.setSpacing(6)
        self.control_layout.setObjectName("control_layout")
        self.cb_device = QtWidgets.QComboBox(self.central_widget)
        self.cb_device.setEditable(False)
        self.cb_device.setObjectName("cb_device")
        self.cb_device.addItem("")
        self.cb_device.addItem("")
        self.cb_device.addItem("")
        self.control_layout.addWidget(self.cb_device, 2, 2, 1, 1)
        self.lb_num_images_max = QtWidgets.QLabel(self.central_widget)
        self.lb_num_images_max.setObjectName("lb_num_images_max")
        self.control_layout.addWidget(self.lb_num_images_max, 3, 0, 1, 1)
        self.lb_saved_height = QtWidgets.QLabel(self.central_widget)
        self.lb_saved_height.setObjectName("lb_saved_height")
        self.control_layout.addWidget(self.lb_saved_height, 6, 0, 1, 1)
        self.lb_num_images = QtWidgets.QLabel(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_num_images.sizePolicy().hasHeightForWidth())
        self.lb_num_images.setSizePolicy(sizePolicy)
        self.lb_num_images.setObjectName("lb_num_images")
        self.control_layout.addWidget(self.lb_num_images, 3, 3, 1, 1)
        self.edit_saved_height = QtWidgets.QLineEdit(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_saved_height.sizePolicy().hasHeightForWidth())
        self.edit_saved_height.setSizePolicy(sizePolicy)
        self.edit_saved_height.setObjectName("edit_saved_height")
        self.control_layout.addWidget(self.edit_saved_height, 6, 2, 1, 1)
        self.btn_record = QtWidgets.QPushButton(self.central_widget)
        self.btn_record.setObjectName("btn_record")
        self.control_layout.addWidget(self.btn_record, 8, 2, 1, 1)
        self.lb_saved_width = QtWidgets.QLabel(self.central_widget)
        self.lb_saved_width.setObjectName("lb_saved_width")
        self.control_layout.addWidget(self.lb_saved_width, 5, 0, 1, 1)
        self.btn_open = QtWidgets.QPushButton(self.central_widget)
        self.btn_open.setObjectName("btn_open")
        self.control_layout.addWidget(self.btn_open, 8, 0, 1, 1)
        self.lb_device = QtWidgets.QLabel(self.central_widget)
        self.lb_device.setObjectName("lb_device")
        self.control_layout.addWidget(self.lb_device, 2, 0, 1, 1)
        self.edit_num_images_max = QtWidgets.QLineEdit(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_num_images_max.sizePolicy().hasHeightForWidth())
        self.edit_num_images_max.setSizePolicy(sizePolicy)
        self.edit_num_images_max.setObjectName("edit_num_images_max")
        self.control_layout.addWidget(self.edit_num_images_max, 3, 2, 1, 1)
        self.edit_saved_width = QtWidgets.QLineEdit(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_saved_width.sizePolicy().hasHeightForWidth())
        self.edit_saved_width.setSizePolicy(sizePolicy)
        self.edit_saved_width.setObjectName("edit_saved_width")
        self.control_layout.addWidget(self.edit_saved_width, 5, 2, 1, 1)
        self.lb_filename_prefix = QtWidgets.QLabel(self.central_widget)
        self.lb_filename_prefix.setObjectName("lb_filename_prefix")
        self.control_layout.addWidget(self.lb_filename_prefix, 7, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setObjectName("lineEdit")
        self.control_layout.addWidget(self.lineEdit, 7, 2, 1, 1)
        self.main_layout.addLayout(self.control_layout)
        self.lb_status = QtWidgets.QLabel(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_status.sizePolicy().hasHeightForWidth())
        self.lb_status.setSizePolicy(sizePolicy)
        self.lb_status.setObjectName("lb_status")
        self.main_layout.addWidget(self.lb_status)
        self.view_layout = QtWidgets.QHBoxLayout()
        self.view_layout.setSpacing(6)
        self.view_layout.setObjectName("view_layout")
        self.lb_image = QtWidgets.QLabel(self.central_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_image.sizePolicy().hasHeightForWidth())
        self.lb_image.setSizePolicy(sizePolicy)
        self.lb_image.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_image.setObjectName("lb_image")
        self.view_layout.addWidget(self.lb_image)
        self.main_layout.addLayout(self.view_layout)
        self.verticalLayout.addLayout(self.main_layout)
        MainWindow.setCentralWidget(self.central_widget)
        self.tool_bar = QtWidgets.QToolBar(MainWindow)
        self.tool_bar.setObjectName("tool_bar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.tool_bar)
        self.menu_bar = QtWidgets.QMenuBar(MainWindow)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 1123, 20))
        self.menu_bar.setObjectName("menu_bar")
        MainWindow.setMenuBar(self.menu_bar)
        self.actionCopy = QtWidgets.QAction(MainWindow)
        self.actionCopy.setObjectName("actionCopy")
        self.actionClearImage = QtWidgets.QAction(MainWindow)
        self.actionClearImage.setObjectName("actionClearImage")
        self.actionOpenImage = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/blue-folder-open-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpenImage.setIcon(icon)
        self.actionOpenImage.setObjectName("actionOpenImage")
        self.actionSaveImage = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSaveImage.setIcon(icon1)
        self.actionSaveImage.setObjectName("actionSaveImage")
        self.actionInvertColors = QtWidgets.QAction(MainWindow)
        self.actionInvertColors.setObjectName("actionInvertColors")
        self.actionFlipHorizontal = QtWidgets.QAction(MainWindow)
        self.actionFlipHorizontal.setObjectName("actionFlipHorizontal")
        self.actionFlipVertical = QtWidgets.QAction(MainWindow)
        self.actionFlipVertical.setObjectName("actionFlipVertical")
        self.actionNewImage = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/document-image.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionNewImage.setIcon(icon2)
        self.actionNewImage.setObjectName("actionNewImage")
        self.actionBold = QtWidgets.QAction(MainWindow)
        self.actionBold.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/edit-bold.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionBold.setIcon(icon3)
        self.actionBold.setObjectName("actionBold")
        self.actionItalic = QtWidgets.QAction(MainWindow)
        self.actionItalic.setCheckable(True)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/edit-italic.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionItalic.setIcon(icon4)
        self.actionItalic.setObjectName("actionItalic")
        self.actionUnderline = QtWidgets.QAction(MainWindow)
        self.actionUnderline.setCheckable(True)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/edit-underline.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUnderline.setIcon(icon5)
        self.actionUnderline.setObjectName("actionUnderline")
        self.actionFillShapes = QtWidgets.QAction(MainWindow)
        self.actionFillShapes.setCheckable(True)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/paint-can-color.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFillShapes.setIcon(icon6)
        self.actionFillShapes.setObjectName("actionFillShapes")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ImageStudio"))
        self.cb_device.setCurrentText(_translate("MainWindow", "0"))
        self.cb_device.setItemText(0, _translate("MainWindow", "0"))
        self.cb_device.setItemText(1, _translate("MainWindow", "1"))
        self.cb_device.setItemText(2, _translate("MainWindow", "2"))
        self.lb_num_images_max.setText(_translate("MainWindow", "num_images_max:"))
        self.lb_saved_height.setText(_translate("MainWindow", "Saved height:"))
        self.lb_num_images.setText(_translate("MainWindow", "num_images"))
        self.btn_record.setText(_translate("MainWindow", "Record"))
        self.lb_saved_width.setText(_translate("MainWindow", "Saved width:"))
        self.btn_open.setText(_translate("MainWindow", "Open"))
        self.lb_device.setText(_translate("MainWindow", "Device:"))
        self.lb_filename_prefix.setText(_translate("MainWindow", "Filename prefix"))
        self.lineEdit.setText(_translate("MainWindow", "class_memo"))
        self.lb_status.setText(_translate("MainWindow", "Status"))
        self.lb_image.setText(_translate("MainWindow", "Image"))
        self.tool_bar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionCopy.setText(_translate("MainWindow", "Copy"))
        self.actionCopy.setShortcut(_translate("MainWindow", "Ctrl+C"))
        self.actionClearImage.setText(_translate("MainWindow", "Clear Image"))
        self.actionOpenImage.setText(_translate("MainWindow", "Open Image..."))
        self.actionSaveImage.setText(_translate("MainWindow", "Save Image As..."))
        self.actionInvertColors.setText(_translate("MainWindow", "Invert Colors"))
        self.actionFlipHorizontal.setText(_translate("MainWindow", "Flip Horizontal"))
        self.actionFlipVertical.setText(_translate("MainWindow", "Flip Vertical"))
        self.actionNewImage.setText(_translate("MainWindow", "New Image"))
        self.actionBold.setText(_translate("MainWindow", "Bold"))
        self.actionBold.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionItalic.setText(_translate("MainWindow", "Italic"))
        self.actionItalic.setShortcut(_translate("MainWindow", "Ctrl+I"))
        self.actionUnderline.setText(_translate("MainWindow", "Underline"))
        self.actionFillShapes.setText(_translate("MainWindow", "Fill Shapes?"))


